project:
  type: website
  output-dir: docs
  render: 
   - "*.qmd"


website:
  title: "Machine Learning Notes"
  repo-url: "https://github.com/joshuafayallen/machine-learning-notes"
  repo-actions: [edit, issue]
  page-navigation: true 
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Notes

  sidebar: 
   - title: "Notes"
     style: 'floating'
     contents: 
        - SQL.qmd
        - data-viz.qmd
        - linear-regression.qmd
        - classification.qmd
        - Bayesian-Stats.qmd
        - Causal-Inference.qmd
        - tree-based-methods.qmd
        - unsupervised-learning.qmd
        - Neural-Networks.qmd
    

bibliography: ref.bib
format:
  html:
    theme:
      - cosmo
execute: 
  message: false
  warning: false
  results: 'hide'
  freeze: auto
  cache: true



